const base = 4;

export const spacing = {
  xs: base, // 4
  s: base * 2, // 8
  m: base * 4, // 16
  l: base * 8, // 32
  xl: base * 12, // 48
};

export const margins = {
  xs: { margin: spacing.xs },
  s: { margin: spacing.s },
  m: { margin: spacing.m },
  l: { margin: spacing.l },
  xl: { margin: spacing.xl },
  hxs: { marginHorizontal: spacing.xs },
  hs: { marginHorizontal: spacing.s },
  hm: { marginHorizontal: spacing.m },
  hl: { marginHorizontal: spacing.l },
  hxl: { marginHorizontal: spacing.xl },
  vxs: { marginVertical: spacing.xs },
  vs: { marginVertical: spacing.s },
  vm: { marginVertical: spacing.m },
  vl: { marginVertical: spacing.l },
  vxl: { marginVertical: spacing.xl },
  txs: { marginTop: spacing.xs },
  ts: { marginTop: spacing.s },
  tm: { marginTop: spacing.m },
  tl: { marginTop: spacing.l },
  txl: { marginTop: spacing.xl },
  bxs: { marginBottom: spacing.xs },
  bs: { marginBottom: spacing.s },
  bm: { marginBottom: spacing.m },
  bl: { marginBottom: spacing.l },
  bxl: { marginBottom: spacing.xl },
  rxs: { marginRight: spacing.xs },
  rs: { marginRight: spacing.s },
  rm: { marginRight: spacing.m },
  rl: { marginRight: spacing.l },
  rxl: { marginRight: spacing.xl },
  lxs: { marginLeft: spacing.xs },
  ls: { marginLeft: spacing.s },
  lm: { marginLeft: spacing.m },
  ll: { marginLeft: spacing.l },
  lxl: { marginLeft: spacing.xl },
};

export const paddings = {
  xs: { padding: spacing.xs },
  s: { padding: spacing.s },
  m: { padding: spacing.m },
  l: { padding: spacing.l },
  xl: { padding: spacing.xl },
  hxs: { paddingHorizontal: spacing.xs },
  hs: { paddingHorizontal: spacing.s },
  hm: { paddingHorizontal: spacing.m },
  hl: { paddingHorizontal: spacing.l },
  hxl: { paddingHorizontal: spacing.xl },
  vxs: { paddingVertical: spacing.xs },
  vs: { paddingVertical: spacing.s },
  vm: { paddingVertical: spacing.m },
  vl: { paddingVertical: spacing.l },
  vxl: { paddingVertical: spacing.xl },
  txs: { paddingTop: spacing.xs },
  ts: { paddingTop: spacing.s },
  tm: { paddingTop: spacing.m },
  tl: { paddingTop: spacing.l },
  txl: { paddingTop: spacing.xl },
  bxs: { paddingBottom: spacing.xs },
  bs: { paddingBottom: spacing.s },
  bm: { paddingBottom: spacing.m },
  bl: { paddingBottom: spacing.l },
  bxl: { paddingBottom: spacing.xl },
  rxs: { paddingRight: spacing.xs },
  rs: { paddingRight: spacing.s },
  rm: { paddingRight: spacing.m },
  rl: { paddingRight: spacing.l },
  rxl: { paddingRight: spacing.xl },
  lxs: { paddingLeft: spacing.xs },
  ls: { paddingLeft: spacing.s },
  lm: { paddingLeft: spacing.m },
  ll: { paddingLeft: spacing.l },
  lxl: { paddingLeft: spacing.xl },
};
